layout_spectrum: 0.6833200762048364
typography_spectrum: 0.47552842437289655
color:
  brandStrength: 0.9019807428121567
  lightness: 0.7858455826062709
  saturation: 0.9955508669372648
  rhythmicContrast: 0.882336524548009
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
name: Trisha Arora
navigation:
  - name: About Trisha
    url: trishaarora.com
    type: external
title: 'Photography, Design, and Code'
description: by Trisha Arora
