typography_spectrum: 0.892202784307301
color:
  brandStrength: 0.366606657858938
  lightness: 0.9065653102006763
  saturation: 0.2906677566934377
  rhythmicContrast: 0.9334702750202268
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.22140352078713477
name: Trisha Arora
navigation:
  - name: About Trisha
    url: trishaarora.com
    type: external
title: 'Photography, Design, and Code'
description: by Trisha Arora
